name: day15_shoes
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.18.0
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.2
  get: ^4.6.5
  firebase_auth: ^4.3.0
  firebase_storage: ^11.3.0 # Update the version here
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/